### ISSUE TITLE
restart button does not have any functionality

### ISSUE THREAD

**Issue by mrtrkmn** [gianmarcomennecozzi/grpc-vue-go#233]
![image](https://user-images.githubusercontent.com/13614433/179374270-61f64d9a-ecc5-4cf1-b507-2f4260cdb48a.png)

Restart button in teams page of an event does not have any functionality.
Fix the issue; either remove it, or provide expected functionality.

**Comment by Mikkelhost** [comment]
I would say just remove it, i don't think we will ever need to restart all containers in an event at once.

**Comment by mrtrkmn** [comment]
Closed with #234
