### ISSUE TITLE
user management page for webclient 

### ISSUE THREAD

**Issue by mrtrkmn** [gianmarcomennecozzi/grpc-vue-go#27]
Some new gRPC calls introduced with [recent changes](https://github.com/aau-network-security/haaukins/pull/403), which means, now we can delete, modifypasswd, and list users who are willing to use Haaukins for their events. I think, a proper user management page might look like WordPress management page like this, 

<img width="1181" alt="Screenshot 2020-05-21 at 20 08 10" src="https://user-images.githubusercontent.com/13614433/82585521-cd510b00-9b9e-11ea-94c1-d3036c3e9b7a.png">

This will remove the barrier of creating users by me or by @gianmarcomennecozzi, anyone who has admin privileges can modify user information. 

I hope, this will remove the barrier for any administrator who are using webclient. I am curious about your opinion @gianmarcomennecozzi. Let me know when you check the issue :) We can have a discussion or call.

**Comment by gianmarcomennecozzi** [comment]
I have sees the new user function you made and i definitely agree with you. We need a user management page and the one that look like WordPress it's good. I will add this issue on my List TODO
