### ISSUE TITLE
remove nginx, use only envoy

### ISSUE THREAD

**Issue by mrtrkmn** [gianmarcomennecozzi/grpc-vue-go#40]
I think, it is possible to remove nginx from docker compose service and go for only envoy, no need to have them both, they have some common  points however envoy's perspective is different.  Although it is different, I think, it can be used for both handling gRPC and HTTP/1 requests thanks to [envoy filters](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/http_filters).

What do you think about this @gianmarcomennecozzi ?

**Comment by gianmarcomennecozzi** [comment]
if it something possible to do it would be nice to remove nginx. have you found any example about that?
